spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?charEncoding=utf-8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
jpa:
  database: MySQL
  show-sql: true
  hibernate:
    naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy